version: '2'
services:
   freeswitch:
     hostname: freeswitch
     container_name: freeswitch
     network_mode: 'host'
     restart: always
    #  build: ./freeswitch
     build:
      context: ./freeswitch
      dockerfile: Dockerfile.additional.modules

     logging:
       options:
         max-size: 50m
     env_file:
       - .env-local
     ports:
      - '5060:5060'
      - '5061:5061'
      - '5060:5060/udp'
      - '5061:5061/udp'
      - '5080:5080'
      - '5081:5081'
      - '5080:5080/udp'
      - '5081:5081/udp'
      - '6060:6060'
      - '6061:6061'
      - '6060:6060/udp'
      - '6061:6061/udp'
      - '16384-16394:16384-16394/udp'
      - '8080:8080'
     volumes:
      - ./freeswitch_configuration/conf:/usr/local/freeswitch/conf
      - ./freeswitch_configuration/db:/usr/local/freeswitch/db
      - ./freeswitch_configuration/log:/usr/local/freeswitch/log
      - ./freeswitch_configuration/scripts:/usr/local/freeswitch/scripts
      - ./freeswitch_configuration/store:/usr/local/freeswitch/store
      - ./freeswitch_configuration/google_key.json:/usr/local/freeswitch/google_key.json
      - ./freeswitch_tmp:/tmp

     command: /usr/local/freswitch/bin/freeswitch -nonat -u freeswitch -g freeswitch -conf /usr/local/freeswitch/conf -log /usr/local/freeswitch/log -db /usr/local/freeswitch/db -scripts /usr/local/freeswitch/scripts -storage /usr/local/freeswitch/store
    #  tty: true
